<?php

/**
 * Implements hook_theme().
 *
 * Auto-generate theme hooks for graphql pages and blocks.
 */
function graphql_twig_theme($existing, $type, $theme, $path) {
  /** @var \Drupal\Core\Extension\ThemeHandlerInterface $themeHandler */
  $themeHandler = \Drupal::service('theme_handler');
  $theme = [];
  foreach ($themeHandler->listInfo() as $themeName => $info) {

    // Register twig routes as theme hooks.
    if (isset($info->info['routes'])) {
      foreach ($info->info['routes'] as $name => $route) {
        $theme[$name] = [
          'variables' =>  [
            'graphql_arguments' => [],
            'graphql_ext' => $name,
          ],
          'function' => '_graphql_twig_missing_template',
        ];
      }
    }

    // Register twig blocks as theme hooks.
    if (isset($info->info['blocks'])) {
      foreach ($info->info['blocks'] as $name => $block) {
        $theme[$name] = [
          'variables' =>  [
            'graphql_arguments' => [],
            'graphql_ext' => $name,
          ],
          'function' => '_graphql_twig_missing_template',
        ];
      }
    }

  }
  return $theme;
}

/**
 * Emits an error message if a dynamic route template is missing.
 */
function _graphql_twig_missing_template($variables) {
  return '<div class="graphql-twig-errors">' . t('Missing template for %ext.', [
    '%ext' => $variables['graphql_ext'],
  ]) . '</div>';
}
