graphql_block:
  type: block_settings
  label: 'GraphQL block'

block.settings.graphql_twig:*:
  type: block_settings
  label: 'GraphQL block'
  mapping:
    graphql_block:
      type: sequence
      sequence:
        type: mapping
        mapping:
          key:
            type: string
          value:
            type: string

graphql_twig.settings:
  type: config_object
  label: 'GraphQL Twig settings'
  mapping:
    debug_placement:
      type: string
      label: 'Notification email address'
